spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
jwt:
  signing-key: b3$Ql^8DBx

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO